/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormulaEditorPanel.java
 *
 * Created on 2009-1-9, 22:30:28
 */

package org.jhrcore.ui;

import org.jhrcore.ui.listener.IPickFormulaEditorListener;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author DB2INST3
 */
public class FormulaEditorPanel extends javax.swing.JPanel {
    private String cur_operator;
    private List<IPickFormulaEditorListener> iPickFormulaEditorListeners = new ArrayList<IPickFormulaEditorListener>();
    
    public void addPickFormulaEditorListener(IPickFormulaEditorListener listener){
        iPickFormulaEditorListeners.add(listener);
    }
    public void delPickFormulaEditorListener(IPickFormulaEditorListener listener){
        iPickFormulaEditorListeners.remove(listener);
    }
    /** Creates new form FormulaEditorPanel */
    public FormulaEditorPanel() {
        initComponents();
        setupEvents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn0 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btn17 = new javax.swing.JButton();
        btn18 = new javax.swing.JButton();
        btn19 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn23 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        btn24 = new javax.swing.JButton();
        btn25 = new javax.swing.JButton();
        btn26 = new javax.swing.JButton();
        btn27 = new javax.swing.JButton();
        btn28 = new javax.swing.JButton();
        btn29 = new javax.swing.JButton();
        btn30 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("ÔËËã·ûºÅ"));
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setPreferredSize(new java.awt.Dimension(180, 228));

        btn0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_0.png"))); // NOI18N
        btn0.setIconTextGap(2);
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_1.png"))); // NOI18N
        btn1.setIconTextGap(2);

        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_2.png"))); // NOI18N
        btn2.setIconTextGap(2);

        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_3.png"))); // NOI18N
        btn3.setIconTextGap(2);

        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_4.png"))); // NOI18N
        btn4.setIconTextGap(2);

        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_5.png"))); // NOI18N
        btn5.setIconTextGap(2);

        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_6.png"))); // NOI18N
        btn6.setIconTextGap(2);

        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_7.png"))); // NOI18N
        btn7.setIconTextGap(2);

        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_8.png"))); // NOI18N
        btn8.setIconTextGap(2);

        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_9.png"))); // NOI18N
        btn9.setIconTextGap(2);

        btn10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_10.png"))); // NOI18N
        btn10.setIconTextGap(2);

        btn11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_11.png"))); // NOI18N
        btn11.setIconTextGap(2);

        btn12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_14.png"))); // NOI18N
        btn12.setIconTextGap(2);

        btn13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_15.png"))); // NOI18N
        btn13.setIconTextGap(2);

        btn14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_12.png"))); // NOI18N
        btn14.setIconTextGap(2);

        btn15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_13.png"))); // NOI18N
        btn15.setIconTextGap(2);

        btn16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_16.png"))); // NOI18N
        btn16.setIconTextGap(2);

        btn17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_17.png"))); // NOI18N
        btn17.setIconTextGap(2);

        btn18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_18.png"))); // NOI18N
        btn18.setIconTextGap(2);

        btn19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_19.png"))); // NOI18N
        btn19.setIconTextGap(2);

        btn20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_20.png"))); // NOI18N
        btn20.setIconTextGap(2);

        btn21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_21.png"))); // NOI18N
        btn21.setIconTextGap(2);

        btn23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_23.png"))); // NOI18N
        btn23.setIconTextGap(2);

        btn22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_22.png"))); // NOI18N
        btn22.setIconTextGap(2);

        btn24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_24.png"))); // NOI18N
        btn24.setIconTextGap(2);

        btn25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_25.png"))); // NOI18N
        btn25.setIconTextGap(2);

        btn26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_26.png"))); // NOI18N
        btn26.setIconTextGap(2);

        btn27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_27.png"))); // NOI18N
        btn27.setIconTextGap(2);

        btn28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_28.png"))); // NOI18N
        btn28.setIconTextGap(2);

        btn29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_29.png"))); // NOI18N
        btn29.setIconTextGap(2);

        btn30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/formula_30.png"))); // NOI18N
        btn30.setIconTextGap(2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(btn24, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(btn25, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(btn17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(btn18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(btn19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(btn29, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn30, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(btn22, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn28, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn23, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(btn15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(btn27, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(btn26, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn26, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn24, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn25, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn27, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn29, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn30, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn28, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn23, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_btn0ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn17;
    private javax.swing.JButton btn18;
    private javax.swing.JButton btn19;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btn23;
    private javax.swing.JButton btn24;
    private javax.swing.JButton btn25;
    private javax.swing.JButton btn26;
    private javax.swing.JButton btn27;
    private javax.swing.JButton btn28;
    private javax.swing.JButton btn29;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn30;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    // End of variables declaration//GEN-END:variables
    private void setupEvents(){
        btn0.addActionListener(new ActionListener(){
            
            public void actionPerformed(ActionEvent e) {
                cur_operator = "0";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn1.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = "1";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }
            
        });
        btn2.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = "2";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn3.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = "3";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn4.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = "4";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn5.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = "5";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn6.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = "6";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn7.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = "7";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn8.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = "8";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn9.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = "9";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn10.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = "(";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn11.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = ")";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn12.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = "*";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn13.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = "/";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn14.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = "+";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn15.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = "-";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn16.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = ">";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn17.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = ">=";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn18.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = "<";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn19.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = "<=";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn20.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = "Sum";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn21.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = "Count";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn22.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = "Min";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn23.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = "Avg";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn24.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = "and";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn25.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = "or";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn26.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = "like";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn27.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = "Not In";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn28.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = "In";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn29.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = "Where";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        btn30.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                cur_operator = "Max";
                for(IPickFormulaEditorListener listener:iPickFormulaEditorListeners)
                    listener.pickEditor(cur_operator);
            }

        });
        
    }
}
