/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ModuleReportPanel.java
 *
 * Created on 2009-12-1, 13:44:47
 */
package org.jhrcore.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import org.jhrcore.client.CommUtil;
import org.jhrcore.util.ComponentUtil;
import org.jhrcore.client.report.ReportCheckModel;
import org.jhrcore.client.report.ReportPanel;
import org.jhrcore.entity.A01;
import org.jhrcore.entity.report.ReportDef;
import org.jhrcore.ui.action.CloseAction;
import org.jhrcore.ui.renderer.HRRendererView;

/**
 *
 * @author mxliteboss
 */
public class ModuleReportPanel extends javax.swing.JPanel {

    private ReportCheckModel reportModel;
    private String module_code;
    private List list;
    private HashMap hm;
    private JTree reportTree;

    /** Creates new form ModuleReportPanel */
    public ModuleReportPanel(String module_code, List list) {
        this.module_code = module_code;
        this.list = list;
        initComponents();
        initOthers();
        setupEvents();
    }

    public ModuleReportPanel(String module_code, HashMap hm) {
        this.module_code = module_code;
        this.hm = hm;
        initComponents();
        initOthers();
        setupEvents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btnExcute = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        pnlReport = new javax.swing.JPanel();

        btnExcute.setText("执行");

        btnCancel.setText("取消");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addComponent(btnExcute)
                .addGap(18, 18, 18)
                .addComponent(btnCancel)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcute)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlReport.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlReport, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlReport, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnExcute;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlReport;
    // End of variables declaration//GEN-END:variables

    private void initOthers() {
        List reports = CommUtil.fetchEntities("select rd from ReportDef rd ,ReportModule rm where rd.reportDef_key=rm.reportDef_key and rm.module_flag='" + module_code + "' and rm.code='comm' order by rd.report_class");
        reportModel = new ReportCheckModel(reports);
        reportTree = new JTree(reportModel);
        pnlReport.add(new JScrollPane(reportTree));
        reportTree.setShowsRootHandles(true);
        reportTree.setRootVisible(false);
        HRRendererView.getReportMap(reportTree).initTree(reportTree);
        ComponentUtil.initTreeSelection(reportTree);
    }

    private void setupEvents() {
        reportTree.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() != 2) {
                    return;
                }
                excute_report();
            }
        ;
        });
        btnExcute.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                excute_report();
            }
        });
        CloseAction.doCloseAction(btnCancel);
    }

    private void excute_report() {
        if (reportTree.getSelectionPath().getLastPathComponent() == null) {
            return;
        }
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) reportTree.getSelectionPath().getLastPathComponent();
        Object obj = node.getUserObject();
        if (obj instanceof ReportDef) {
            try {
                ReportDef reportDef = (ReportDef) obj;
                Map hm = new HashMap();
                if (list != null && list.size() > 0) {
                    int len = list.size();
                    String[] a0190s = new String[len];
                    for (int i = 0; i < len; i++) {
                        Object data = list.get(i);
                        if (data instanceof A01) {
                            a0190s[i] = ((A01) data).getA0190();
                        } else {
                            a0190s[i] = data.toString();
                        }
                    }
                    hm.put("人员编号", a0190s);
                } else if (this.hm != null) {
                    hm = this.hm;
                }
                ReportPanel.excute_report((JFrame) JOptionPane.getFrameForComponent(reportTree), reportDef, hm);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    public static void showModuleReport(JFrame jf, String module_code, List list) {
        ModuleReportPanel pnlMr = new ModuleReportPanel(module_code, list);
        ModelFrame.showModel(jf, pnlMr, true, "通用报表", 500, 330);
    }

    public static void showModuleReport(JFrame jf, String module_code, HashMap hm) {
        ModuleReportPanel pnlMr = new ModuleReportPanel(module_code, hm);
        ModelFrame.showModel(jf, pnlMr, true, "通用报表", 500, 330);
    }
}
