/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ShowFieldDlg.java
 *
 * Created on 2009-4-14, 15:40:44
 */
package org.jhrcore.ui;

import java.awt.event.MouseEvent;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Enumeration;
import java.util.HashSet;
import java.util.Hashtable;
import java.util.List;
import java.util.Set;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreePath;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.SwingBindings;
import org.jhrcore.client.CommUtil;
import org.jhrcore.util.SysUtil;
import org.jhrcore.client.UserContext;
import org.jhrcore.util.UtilTool;
import org.jhrcore.entity.base.TempFieldInfo;
import org.jhrcore.entity.salary.ValidateSQLResult;
import org.jhrcore.entity.showstyle.ShowFieldGroup;
import org.jhrcore.entity.showstyle.ShowScheme;
import org.jhrcore.entity.showstyle.ShowSchemeDetail;
import org.jhrcore.iservice.impl.CommImpl;
import org.jhrcore.rebuild.EntityBuilder;
import org.jhrcore.ui.renderer.HRRendererView;
import org.jhrcore.util.ComponentUtil;
import org.jhrcore.util.MsgUtil;

/**
 *
 * @author mxliteboss
 */
public class ShowFieldDialog2 extends javax.swing.JDialog {

    private Class cur_class;
    private final String module_code = "HRUIComm.ShowField";
    // 所有字段
    private List<TempFieldInfo> list_all_field = new ArrayList<TempFieldInfo>();
    // 默认字段
    private List<TempFieldInfo> list_default_field = new ArrayList<TempFieldInfo>();
    // 当前编辑的界面风格
    private ShowScheme curShowScheme = null;
    private List<String> fields = new ArrayList<String>();
    private JTree fieldTree;
    private Hashtable<String, TempFieldInfo> all_field_infos = new Hashtable<String, TempFieldInfo>();
    private ShowFieldTreeModel fieldModel;
    private JTree showTree;
    private String entity_name;
    private DefaultMutableTreeNode rootNode = new DefaultMutableTreeNode("字段列表");
    private boolean click_ok = false;
    private JComboBoxBinding scheme_binding;
    private List scheme_list = new ArrayList();

    public boolean isClick_ok() {
        return click_ok;
    }

    public List<String> getFields() {
        return fields;
    }

    public ShowScheme getCurShowScheme() {
        return curShowScheme;
    }

    public ShowFieldDialog2() {
        initComponents();
    }

    public ShowFieldDialog2(java.awt.Frame parent, Class show_class, List<TempFieldInfo> all_fields, List<TempFieldInfo> default_fields, String module_code, ShowScheme showScheme, List scheme_list) {
        super(parent);
        this.setTitle("设置显示字段");
        cur_class = show_class;
//        this.module_code = module_code;
        entity_name = module_code + "." + cur_class.getSimpleName();
        list_all_field.addAll(all_fields);
        list_default_field.addAll(default_fields);
        this.curShowScheme = showScheme;
        if (scheme_list != null) {
            this.scheme_list.addAll(scheme_list);
        }
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        initComponents();
        initOthers();
        setupEvents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        jcbGroup = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlField = new javax.swing.JPanel();
        btnAddall = new javax.swing.JButton();
        btnAddSchemeDetail = new javax.swing.JButton();
        btnDelSchemeDetail = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnlRight = new javax.swing.JPanel();
        btnUp = new javax.swing.JButton();
        btnDown = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        toolbar = new javax.swing.JToolBar();
        btnSave = new javax.swing.JButton();
        btnRename = new javax.swing.JButton();
        btnSaveAs = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnFieldGroup = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cb_scheme = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        btnClose.setText("关闭");
        btnClose.setName("btnClose"); // NOI18N

        btnOk.setText("应用");

        jcbGroup.setText("启用分组");

        jLabel3.setText("说明：未分组字段的默认组名为【未分组】");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbGroup)
                .addGap(18, 18, 18)
                .addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbGroup)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("未选字段：");

        pnlField.setLayout(new java.awt.BorderLayout());

        btnAddall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/select_all.png"))); // NOI18N

        btnAddSchemeDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/select_one.png"))); // NOI18N
        btnAddSchemeDetail.setName("btnRemove"); // NOI18N
        btnAddSchemeDetail.setPreferredSize(new java.awt.Dimension(22, 22));

        btnDelSchemeDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/remove_one.png"))); // NOI18N

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/remove_all.png"))); // NOI18N

        jLabel1.setText("已选字段：");

        pnlRight.setLayout(new java.awt.BorderLayout());

        btnUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/move_up.png"))); // NOI18N
        btnUp.setMaximumSize(new java.awt.Dimension(22, 22));
        btnUp.setMinimumSize(new java.awt.Dimension(22, 22));
        btnUp.setPreferredSize(new java.awt.Dimension(22, 22));

        btnDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/move_down.png"))); // NOI18N
        btnDown.setMaximumSize(new java.awt.Dimension(22, 22));
        btnDown.setMinimumSize(new java.awt.Dimension(22, 22));
        btnDown.setPreferredSize(new java.awt.Dimension(22, 22));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pnlField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddall, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnDelSchemeDetail, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                .addComponent(btnClear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAddSchemeDetail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(187, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnUp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDown, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(193, 193, 193))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pnlRight, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnAddall, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAddSchemeDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDelSchemeDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlRight, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pnlField, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)))
        );

        toolbar.setFloatable(false);
        toolbar.setRollover(true);
        toolbar.setMaximumSize(new java.awt.Dimension(186, 23));
        toolbar.setMinimumSize(new java.awt.Dimension(186, 23));
        toolbar.setPreferredSize(new java.awt.Dimension(186, 23));

        btnSave.setText("保存");
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnSave);

        btnRename.setText("重命名");
        btnRename.setFocusable(false);
        btnRename.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRename.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnRename);

        btnSaveAs.setText("另存为");
        btnSaveAs.setFocusable(false);
        btnSaveAs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSaveAs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnSaveAs);

        btnDel.setText("删除");
        btnDel.setFocusable(false);
        btnDel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnDel);

        btnFieldGroup.setText("字段分组");
        btnFieldGroup.setFocusable(false);
        btnFieldGroup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFieldGroup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnFieldGroup);

        jLabel4.setText(" 显示方案：");
        jLabel4.setMaximumSize(new java.awt.Dimension(80, 15));
        toolbar.add(jLabel4);

        cb_scheme.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_scheme.setMaximumSize(new java.awt.Dimension(150, 32767));
        toolbar.add(cb_scheme);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initOthers() {
        ComponentUtil.setSysFuntion(this, module_code);
        if (list_all_field.isEmpty()) {
            List<TempFieldInfo> list = EntityBuilder.getCommFieldInfoListOf(cur_class, EntityBuilder.COMM_FIELD_VISIBLE);
            for (TempFieldInfo tfi : list) {
                list_all_field.add(tfi);
            }
        }
        int i = 0;
        for (TempFieldInfo tfi : list_all_field) {
            i++;
            tfi.setOrder_no(i);
            all_field_infos.put(tfi.getEntity_name() + "." + tfi.getField_name(), tfi);
        }
        fieldModel = new ShowFieldTreeModel(list_all_field);
        fieldTree = new JTree(fieldModel);
        HRRendererView.getCommMap().initTree(fieldTree, TreeSelectMod.nodeManySelectMod);
        fieldTree.setRootVisible(false);
        fieldTree.setShowsRootHandles(true);
        pnlField.add(new JScrollPane(fieldTree), BorderLayout.CENTER);
        if (scheme_list.isEmpty()) {
            scheme_list.addAll(CommUtil.fetchEntities("from ShowScheme ss left join fetch ss.showSchemeDetails ssd where ss.entity_name='" + entity_name + "' and ss.person_code='" + UserContext.person_code + "' "));
        }
        ShowScheme default_scheme = null;
        if (scheme_list.size() > 0) {
            for (Object obj : scheme_list) {
                ShowScheme ss = (ShowScheme) obj;
                if (ss.getShowScheme_key().equals(entity_name + "_default")) {
                    default_scheme = ss;
                }
                if (curShowScheme == null && "1".equals(ss.getDefault_flag())) {
                    curShowScheme = ss;
                    break;
                }
            }
        }
        if (default_scheme == null) {
            scheme_list.add(0, getDefaultScheme());
        } else {
            scheme_list.remove(default_scheme);
            scheme_list.add(0, default_scheme);
        }
        scheme_binding = SwingBindings.createJComboBoxBinding(UpdateStrategy.READ_WRITE, scheme_list, cb_scheme);
        scheme_binding.bind();
        if (curShowScheme == null) {
            curShowScheme = (ShowScheme) scheme_list.get(0);
        }
        int index = scheme_list.indexOf(curShowScheme);
        if (index != -1) {
            cb_scheme.setSelectedIndex(index);
        }
        showTree = new JTree(rootNode);
        HRRendererView.getCommMap().initTree(showTree, TreeSelectMod.nodeManySelectMod);
        pnlRight.add(new JScrollPane(showTree), BorderLayout.CENTER);
        setCurShowScheme(curShowScheme);
        CurUserContext();
        SearchTreeFieldDialog.doQuickSearch("未选字段树", fieldTree);
        SearchTreeFieldDialog.doQuickSearch("已选字段树", showTree);

    }
    //设置当前方案，并根据该方案改变左右字段树显示

    private void setCurShowScheme(ShowScheme curShowScheme) {
        List<TempFieldInfo> list_Selected = new ArrayList<TempFieldInfo>();
        jcbGroup.setSelected(curShowScheme.isGroup_flag());
        List group_list = CommUtil.fetchEntities("from ShowFieldGroup sfg where sfg.entity_name='" + entity_name + "' and person_code in('sa','" + UserContext.person_code + "') order by sfg.order_no");
        HashSet<String> group_name_list = new HashSet<String>();
        for (Object obj : group_list) {
            ShowFieldGroup sfg = (ShowFieldGroup) obj;
            if (UserContext.person_code.equals(sfg.getPerson_code())) {
                group_name_list.add(sfg.getGroup_name());
            }
        }
        if (group_name_list.isEmpty()) {
            for (Object obj : group_list) {
                ShowFieldGroup sfg = (ShowFieldGroup) obj;
                if (UserContext.sysManName.equals(sfg.getPerson_code())) {
                    group_name_list.add(sfg.getGroup_name());
                }
            }
        }
        fieldModel.rebuild();
        if (curShowScheme.getShowSchemeDetails() != null && curShowScheme.getShowSchemeDetails().size() > 0) {
            List<ShowSchemeDetail> ssd_list = new ArrayList<ShowSchemeDetail>();
            ssd_list.addAll(curShowScheme.getShowSchemeDetails());
            Collections.sort(ssd_list, new Comparator() {

                @Override
                public int compare(Object arg0, Object arg1) {
                    ShowSchemeDetail field0 = (ShowSchemeDetail) arg0;
                    ShowSchemeDetail field1 = (ShowSchemeDetail) arg1;
                    Integer order_no0 = field0.getOrder_no();
                    Integer order_no1 = field1.getOrder_no();
                    return order_no0.compareTo(order_no1);
                }
            });
            for (ShowSchemeDetail ssd : ssd_list) {
                Enumeration enumt = ((DefaultMutableTreeNode) fieldModel.getRoot()).breadthFirstEnumeration();
                while (enumt.hasMoreElements()) {
                    DefaultMutableTreeNode node = (DefaultMutableTreeNode) enumt.nextElement();
                    if (node.getUserObject() instanceof TempFieldInfo) {
                        TempFieldInfo tfi = (TempFieldInfo) node.getUserObject();
                        if ((tfi.getEntity_name() + "." + tfi.getField_name()).equals(ssd.getEntity_name() + "." + ssd.getField_name())) {
                            node.removeFromParent();
                            String group_name = ssd.getField_group();
                            if (group_name != null && !group_name.trim().equals("")) {
                                if (group_name_list.contains(group_name)) {
                                    tfi.setGroup_name(group_name);
                                } else {
                                    tfi.setGroup_name("");
                                    ssd.setField_group("");
                                }
                            } else {
                                tfi.setGroup_name(group_name);
                            }
                            list_Selected.add(tfi);
                            break;
                        }
                    }
                }
            }
        } else {
            for (TempFieldInfo tfi1 : list_default_field) {
                list_Selected.add(tfi1);
                Enumeration enumt = ((DefaultMutableTreeNode) fieldModel.getRoot()).breadthFirstEnumeration();
                while (enumt.hasMoreElements()) {
                    DefaultMutableTreeNode node = (DefaultMutableTreeNode) enumt.nextElement();
                    if (node.getUserObject() instanceof TempFieldInfo) {
                        TempFieldInfo tfi = (TempFieldInfo) node.getUserObject();
                        if (tfi.getField_name().equals(tfi1.getField_name())) {
                            node.removeFromParent();
                            break;
                        }
                    }
                }
            }
        }
        refreshShowTree(list_Selected);
        fieldTree.updateUI();
        fieldTree.expandRow(0);
        fieldTree.setSelectionRow(0);

    }

    private void refreshShowTree(List<TempFieldInfo> select_fields) {
        rootNode.removeAllChildren();
        for (TempFieldInfo tfi : select_fields) {
            DefaultMutableTreeNode node = new DefaultMutableTreeNode(tfi);
            rootNode.add(node);
        }
        showTree.setRootVisible(false);
        showTree.setShowsRootHandles(true);
        ComponentUtil.initTreeSelection(showTree);
    }

    /**
     * 删除已选字段
     * @param all_flag：为True时表示将所有已选字段移除
     */
    private void delShowSchemeDetail(boolean all_flag) {
        List<TempFieldInfo> field_infos = new ArrayList<TempFieldInfo>();
        DefaultMutableTreeNode last_node = null;
        HashSet<DefaultMutableTreeNode> remove_nodes = new HashSet<DefaultMutableTreeNode>();
        if (all_flag) {
            Enumeration enumt = rootNode.breadthFirstEnumeration();
            while (enumt.hasMoreElements()) {
                DefaultMutableTreeNode node = (DefaultMutableTreeNode) enumt.nextElement();
                if (node == rootNode) {
                    continue;
                }
                remove_nodes.add(node);
            }
        } else {
            TreePath[] select_path = showTree.getSelectionPaths();
            if (select_path == null || select_path.length == 0) {
                return;
            }
            for (TreePath tp : select_path) {
                DefaultMutableTreeNode node = (DefaultMutableTreeNode) tp.getLastPathComponent();
                Object obj = node.getUserObject();
                if (obj instanceof String) {
                    Enumeration enumt = node.children();
                    while (enumt.hasMoreElements()) {
                        DefaultMutableTreeNode child = (DefaultMutableTreeNode) enumt.nextElement();
                        if (!remove_nodes.contains(child)) {
                            remove_nodes.add(child);
                        }
                    }
                    remove_nodes.add(node);
                } else if (obj instanceof TempFieldInfo) {
                    if (remove_nodes.contains(node)) {
                        continue;
                    }
                    remove_nodes.add(node);
                }
            }
        }
        List<DefaultMutableTreeNode> nodes = new ArrayList<DefaultMutableTreeNode>();
        for (DefaultMutableTreeNode node : remove_nodes) {
            Object obj = node.getUserObject();
            if (obj instanceof TempFieldInfo) {
                last_node = ComponentUtil.getNextNode(node);
                nodes.add(node);
                field_infos.add((TempFieldInfo) obj);
                node.removeFromParent();
            }
        }
        remove_nodes.removeAll(nodes);
        for (DefaultMutableTreeNode node : remove_nodes) {
            last_node = ComponentUtil.getNextNode(node);
            node.removeFromParent();
        }
        if (last_node != null) {
            showTree.clearSelection();
            showTree.addSelectionPath(new TreePath(last_node.getPath()));
        }
        showTree.updateUI();
        for (TempFieldInfo tfi : field_infos) {
            last_node = fieldModel.addNode(tfi);
        }
        if (last_node != null) {
            fieldTree.clearSelection();
            fieldTree.addSelectionPath(new TreePath(last_node.getPath()));
        }
        fieldTree.updateUI();
    }

    /**
     * 该方法用于增加显示字段
     * @param all_flag：是否将全部字段作为显示字段
     */
    private void addShowSchemeDetail(boolean all_flag) {
        List<TempFieldInfo> field_infos = new ArrayList<TempFieldInfo>();
        DefaultMutableTreeNode next_node = null;
        if (all_flag) {
            Enumeration enumt = ((DefaultMutableTreeNode) fieldModel.getRoot()).breadthFirstEnumeration();
            List<DefaultMutableTreeNode> nodes = new ArrayList<DefaultMutableTreeNode>();
            while (enumt.hasMoreElements()) {
                DefaultMutableTreeNode node = (DefaultMutableTreeNode) enumt.nextElement();
                Object obj = node.getUserObject();
                if (obj instanceof String) {
                    continue;
                }
                TempFieldInfo tfi = (TempFieldInfo) obj;
                field_infos.add(tfi);
                nodes.add(node);
            }
            for (DefaultMutableTreeNode node : nodes) {
                next_node = ComponentUtil.getNextNode(node);
                node.removeFromParent();
            }
        } else {
            TreePath[] select_path = fieldTree.getSelectionPaths();
            Hashtable<String, TreePath> tree_path_keys = new Hashtable<String, TreePath>();
            for (TreePath tp : select_path) {
                DefaultMutableTreeNode node = (DefaultMutableTreeNode) tp.getLastPathComponent();
                if (!(node.getUserObject() instanceof TempFieldInfo)) {
                    Enumeration enumt = node.children();
                    while (enumt.hasMoreElements()) {
                        DefaultMutableTreeNode child = (DefaultMutableTreeNode) enumt.nextElement();
                        TempFieldInfo tfi = (TempFieldInfo) child.getUserObject();
                        if (tree_path_keys.get(tfi.getField_name()) == null) {
                            tree_path_keys.put(tfi.getField_name(), new TreePath(child.getPath()));
                        }
                    }
                } else {
                    tree_path_keys.put(((TempFieldInfo) node.getUserObject()).getField_name(), tp);
                }
            }
            for (TreePath tp : tree_path_keys.values()) {
                Object[] objs = tp.getPath();
                for (Object obj : objs) {
                    if (obj instanceof DefaultMutableTreeNode) {
                        DefaultMutableTreeNode node = (DefaultMutableTreeNode) obj;
                        next_node = ComponentUtil.getNextNode(node);
                        if (node.getUserObject() instanceof TempFieldInfo) {
                            field_infos.add((TempFieldInfo) node.getUserObject());
                            node.removeFromParent();
                        }
                    }
                }
            }
        }
        SysUtil.sortListByInteger(field_infos, "order_no");
        fieldTree.clearSelection();
        if (next_node != null && next_node.getPath() != null) {
            fieldTree.setSelectionPath(new TreePath(next_node.getPath()));
        }
        fieldTree.updateUI();
        DefaultMutableTreeNode child_node = null;
        if (showTree.getSelectionPath() != null && showTree.getSelectionPath().getLastPathComponent() != showTree.getModel().getRoot()) {
            child_node = (DefaultMutableTreeNode) showTree.getLastSelectedPathComponent();
        }
        for (TempFieldInfo tfi : field_infos) {
            next_node = new DefaultMutableTreeNode(tfi);
            if (child_node == null) {
                rootNode.add(next_node);
            } else {
                rootNode.insert(next_node, showTree.getRowForPath(new TreePath(child_node.getPath())) + 1);
                child_node = next_node;
            }
        }
        if (next_node != null) {
            TreeNode[] nodes = next_node.getPath();
            TreePath path = new TreePath(nodes);
            showTree.expandPath(path);
            showTree.setSelectionPath(path);
            showTree.scrollPathToVisible(path);
        }
        showTree.updateUI();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSchemeDetail;
    private javax.swing.JButton btnAddall;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnDelSchemeDetail;
    private javax.swing.JButton btnDown;
    private javax.swing.JButton btnFieldGroup;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnRename;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveAs;
    private javax.swing.JButton btnUp;
    private javax.swing.JComboBox cb_scheme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox jcbGroup;
    private javax.swing.JPanel pnlField;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JToolBar toolbar;
    // End of variables declaration//GEN-END:variables

    private void setupEvents() {
        cb_scheme.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                curShowScheme = null;
                if (cb_scheme.getSelectedItem() != null) {
                    curShowScheme = (ShowScheme) cb_scheme.getSelectedItem();
                    setCurShowScheme(curShowScheme);
                    CurUserContext();
                }
            }
        });
        showTree.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    delShowSchemeDetail(false);
                }
            }
        });
        btnFieldGroup.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                List<TempFieldInfo> select_fields = new ArrayList<TempFieldInfo>();
                Enumeration enumt = rootNode.children();
                while (enumt.hasMoreElements()) {
                    select_fields.add((TempFieldInfo) ((DefaultMutableTreeNode) enumt.nextElement()).getUserObject());
                }
                ShowFieldGroupSetDlg sfgsDlg = new ShowFieldGroupSetDlg(JOptionPane.getFrameForComponent(btnFieldGroup), entity_name, list_all_field, select_fields);
                ContextManager.locateOnMainScreenCenter(sfgsDlg);
                sfgsDlg.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                sfgsDlg.setVisible(true);
                if (sfgsDlg.isClick_ok()) {
                    showTree.updateUI();
                }
            }
        });
        fieldTree.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                if (fieldTree.getSelectionPath() == null) {
                    return;
                }
                if (e.getClickCount() >= 2) {
                    Object obj = ((DefaultMutableTreeNode) fieldTree.getSelectionPath().getLastPathComponent()).getUserObject();
                    if (obj instanceof TempFieldInfo) {
                        addShowSchemeDetail(false);
                    }
                }
            }
        });
        btnOk.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                saveShowScheme(0);
                click_ok = true;
                dispose();
            }
        });
        btnClose.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                click_ok = false;
                dispose();
            }
        });
        btnAddSchemeDetail.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                addShowSchemeDetail(false);
            }
        });

        btnAddall.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                addShowSchemeDetail(true);
            }
        });

        btnDelSchemeDetail.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                delShowSchemeDetail(false);
            }
        });

        btnUp.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                updetail(-1);
            }
        });
        btnDown.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                updetail(1);
            }
        });
        btnClear.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                delShowSchemeDetail(true);
            }
        });
        btnSaveAs.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                saveShowScheme(1);
            }
        });
        btnSave.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                saveShowScheme(2);
            }
        });
        btnRename.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                saveShowScheme(3);
            }
        });
        btnDel.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                delScheme();
            }
        });
    }

    /**
     * 向上/下移动节点顺序
     * @param step：1，向上;-1向下
     */
    private void updetail(int step) {
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) showTree.getLastSelectedPathComponent();
        if (node == null) {
            return;
        }
        Object obj = node.getUserObject();
        if (obj instanceof String) {
            return;
        }
        DefaultMutableTreeNode parent_node = (DefaultMutableTreeNode) node.getParent();
        int child_count = parent_node.getChildCount();
        if (child_count <= 1) {
            return;
        }
        int ind = parent_node.getIndex(node);
        ind = ind + step;
        node.removeFromParent();
        if (ind == -1) {
            parent_node.add(node);
        } else {
            if (ind >= child_count) {
                ind = 0;
            }
            parent_node.insert(node, ind);
        }
        showTree.clearSelection();
        showTree.addSelectionPath(new TreePath(node.getPath()));
        showTree.scrollRowToVisible(ind);
        showTree.updateUI();
    }

    private void delScheme() {
        if (curShowScheme == null || curShowScheme.getShowScheme_key() == null) {
            return;
        }
        if (curShowScheme.getShowScheme_key().equals(entity_name + "_default")) {
            JOptionPane.showMessageDialog(null, "系统方案不允许删除");
            return;
        }
        if (MsgUtil.showNotConfirmDialog("确定要删除该方案吗?")) {
            return;
        }
        ValidateSQLResult result = CommImpl.delShowScheme(curShowScheme);
        if (result.getResult() != 0) {
            curShowScheme = (ShowScheme) CommUtil.fetchEntityBy("from ShowScheme ss left join fetch ss.showSchemeDetails where showScheme_key = '" + curShowScheme.getShowScheme_key() + "'");
            JOptionPane.showMessageDialog(JOptionPane.getFrameForComponent(btnClose), "删除方案失败");
        } else {
            scheme_list.remove(curShowScheme);
            scheme_binding.unbind();
            scheme_binding.bind();
        }
    }

    /**
     * 保存方案
     * @param flag:0:点击应用按钮，若为数据库方案，则保存改变；1：另存方案；2：保存方案；3：改方案名，对于默认空方案不起作用
     */
    private void saveShowScheme(int flag) {
        String newName = null;
        if ((flag == 1) || (flag == 3 && !curShowScheme.getShowScheme_key().equals(entity_name + "_default"))) {
            List<String> fields2 = new ArrayList<String>();
            fields2.add("showScheme_name");
            ShowScheme ss = new ShowScheme();
            ss.setShowScheme_key(curShowScheme.getShowScheme_key());
            ss.setShowScheme_name(curShowScheme.getShowScheme_name());
            if (!BeanPanel.edit(ss, fields2, "方案名称", new ValidateEntity() {

                @Override
                public boolean isEntityValidate(Object obj) {
                    ShowScheme para = (ShowScheme) obj;
                    if (para.getShowScheme_name() == null || "".equals(para.getShowScheme_name().replace(" ", ""))) {
                        JOptionPane.showMessageDialog(null, "请填写方案名称");
                        return false;
                    }
                    if (CommUtil.exists("select 1 from ShowScheme where showScheme_key != '" + para.getShowScheme_key() + "' and  showScheme_name ='" + para.getShowScheme_name() + "' and entity_name='" + entity_name + "' and person_code='" + UserContext.person_code + "'")) {
                        JOptionPane.showMessageDialog(null, "该方案名称已存在");
                        return false;
                    }
                    return true;
                }
            })) {
                return;
            }
            newName = ss.getShowScheme_name();
        }
        newName = (newName == null || newName.trim().equals("")) ? curShowScheme.getShowScheme_name() : newName;
        if (flag == 3) {
            ValidateSQLResult result = CommUtil.excuteSQL("update ShowScheme set showscheme_name='" + newName + "' where showscheme_key='" + curShowScheme.getShowScheme_key() + "'");
            if (result.getResult() == 0) {
                curShowScheme.setShowScheme_name(newName);
                cb_scheme.updateUI();
            } else {
                String old_name = (String) CommUtil.fetchEntityBy("select showScheme_name from ShowScheme where showScheme_key='" + curShowScheme.getShowScheme_key() + "'");
                curShowScheme.setShowScheme_name(old_name);
            }
            return;
        }
        boolean grouped = jcbGroup.isSelected();
        Enumeration enumt = rootNode.breadthFirstEnumeration();
        List<TempFieldInfo> selected_fields = new ArrayList<TempFieldInfo>();
        fields.clear();
        while (enumt.hasMoreElements()) {
            DefaultMutableTreeNode node = (DefaultMutableTreeNode) enumt.nextElement();
            Object obj = node.getUserObject();
            if (obj instanceof TempFieldInfo) {
                TempFieldInfo tfi = (TempFieldInfo) obj;
                selected_fields.add(tfi);
                fields.add(tfi.getField_name());
            }
        }
        if (selected_fields.isEmpty()) {
            JOptionPane.showMessageDialog(JOptionPane.getFrameForComponent(btnOk), "未选择任何字段");
            return;
        }
        ShowScheme ss = curShowScheme;
        if (flag == 1) {
            ss = (ShowScheme) UtilTool.createUIDEntity(ShowScheme.class);
        }
        ss.setShowScheme_name(newName);
        ss.setEntity_name(entity_name);//module_code + "." + cur_class.getSimpleName());
        ss.setPerson_code(UserContext.person_code);
        ss.setUsed_flag(true);
        ss.setGroup_flag(grouped);
        if (flag == 0) {
            ss.setDefault_flag("1");
        }
        Set<ShowSchemeDetail> fields1 = new HashSet<ShowSchemeDetail>();
        int len = selected_fields.size();
        for (int i = 0; i < len; i++) {
            TempFieldInfo tfi = (TempFieldInfo) selected_fields.get(i);
            ShowSchemeDetail ssd = (ShowSchemeDetail) UtilTool.createUIDEntity(ShowSchemeDetail.class);
            ssd.setShowScheme(ss);
            ssd.setField_caption(tfi.getCaption_name());
            ssd.setField_name(tfi.getField_name());
            ssd.setOrder_no(i);
            ssd.setEntity_name(tfi.getEntity_name());
            ssd.setEntity_caption(tfi.getEntity_caption());
            ssd.setField_group(tfi.getGroup_name());
            fields1.add(ssd);
        }
        ss.setShowSchemeDetails(fields1);
        if (flag == 0 && curShowScheme.getShowScheme_key() == null) {
            return;
        }
        ValidateSQLResult result = CommImpl.saveShowScheme(ss, "detail");
        if (result.getResult() == 0) {
            ss.setNew_flag(0);
            boolean existsScheme = false;
            for (Object obj : scheme_list) {
                if (((ShowScheme) obj).getShowScheme_key().equals(ss.getShowScheme_key())) {
                    existsScheme = true;
                    break;
                }
            }
            if (!existsScheme) {
                scheme_list.add(ss);
            }
            scheme_binding.unbind();
            scheme_binding.bind();
            cb_scheme.setSelectedItem(ss);
            cb_scheme.updateUI();
            MsgUtil.showHRSaveSuccessMsg(null);
        } else {
            if (ss.getNew_flag() == 0) {
                ss = (ShowScheme) CommUtil.fetchEntityBy("from ShowScheme ss left join fetch ss.showSchemeDetails where ss.showScheme_key = '" + curShowScheme.getShowScheme_key() + "'");
            }
            JOptionPane.showMessageDialog(JOptionPane.getFrameForComponent(btnClose), "保存方案失败");
        }
    }

    private ShowScheme getDefaultScheme() {
        ShowScheme temp_ss = new ShowScheme();
        temp_ss.setShowScheme_name("");
        temp_ss.setGroup_flag(false);
        temp_ss.setNew_flag(1);
        temp_ss.setShowScheme_key(entity_name + "_default");
        temp_ss.setPerson_code(UserContext.person_code);
        temp_ss.setEntity_name(entity_name);
        temp_ss.setShowScheme_name("系统方案");
        if (list_default_field != null && list_default_field.size() > 0) {
            Set<ShowSchemeDetail> ssds = new HashSet<ShowSchemeDetail>();
            for (TempFieldInfo tfi : list_default_field) {
                ShowSchemeDetail ssd = new ShowSchemeDetail();
                ssd.setShowSchemeDetail_key(UtilTool.getUID());
                ssd.setShowScheme(temp_ss);
                ssd.setEntity_name(tfi.getEntity_name());
                ssd.setField_caption(tfi.getCaption_name());
                ssd.setField_name(tfi.getField_name());
                ssd.setOrder_no(tfi.getOrder_no());
                ssds.add(ssd);
            }
            temp_ss.setShowSchemeDetails(ssds);
        }
        temp_ss.setDefault_flag("1");
        for (Object obj : scheme_list) {
            ShowScheme ss = (ShowScheme) obj;
            if ("1".equals(ss.getDefault_flag())) {
                temp_ss.setDefault_flag("0");
                break;
            }
        }
        CommImpl.saveShowScheme(temp_ss, "detail");
        return temp_ss;
    }

    public List getScheme_list() {
        return scheme_list;
    }

    private void CurUserContext() {
        boolean bo = UserContext.isSA;
        String curname = curShowScheme.getShowScheme_name();
        if ("系统方案".equals(curname)) {
            if (!bo) {
                btnSave.setEnabled(false);
                btnOk.setEnabled(false);
            }
        } else {
            btnSave.setEnabled(true);
            btnOk.setEnabled(true);
        }
    }
}
