/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AnalyseNamePanel.java
 *
 * Created on 2010-3-8, 21:02:47
 */
package org.jhrcore.queryanalysis;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;
import org.jdesktop.swingbinding.SwingBindings;
import org.jhrcore.client.CommUtil;
import org.jhrcore.client.UserContext;
import org.jhrcore.msg.pay.PayAnalyseMsg;
import org.jhrcore.ui.task.IModuleCode;
import org.jhrcore.ui.WizardPanel;
import org.jhrcore.util.ComponentUtil;
import org.jhrcore.util.MsgUtil;

/**
 *
 * @author mxliteboss
 */
public class AnalyseNamePanel extends WizardPanel implements IModuleCode{

    private CommAnalysePara empAnalysePara;
    private String module_code = "PayAnalyse.btnAdd.stept1";

    public AnalyseNamePanel() {
        initComponents();
        ComponentUtil.setSysFuntionNew(this, false);
    }

    /** Creates new form AnalyseNamePanel */
    
    public AnalyseNamePanel(CommAnalysePara empAnalysePara) {
        initComponents();
        this.empAnalysePara = empAnalysePara;
        jTextField1.setText(empAnalysePara.getCommAnalyseScheme().getScheme_name());
        List<String> list = (List<String>) CommUtil.fetchEntities("select distinct group_name from " + empAnalysePara.getCommAnalyseScheme().getClass().getSimpleName() + " where user_code='" + UserContext.person_code + "'");
        list.add(0, "");
        SwingBindings.createJComboBoxBinding(UpdateStrategy.READ, list, jComboBox1).bind();
        if (empAnalysePara.getCommAnalyseScheme().getGroup_name() != null && !empAnalysePara.getCommAnalyseScheme().getGroup_name().trim().equals("")) {
            jComboBox1.setSelectedItem(empAnalysePara.getCommAnalyseScheme().getGroup_name());
        }
        jComboBox1.setEditable(true);
        List data = new ArrayList();
        data.add("否");
        if (empAnalysePara.getQuery_class().getSimpleName().equals("A01") && UserContext.hasFunctionRight("EmpAnalyse.sharecreate")) {
            data.add("是");
        } else if (empAnalysePara.getQuery_class().getSimpleName().equals("Pay") && UserContext.hasFunctionRight("PayAnalyse.sharecreate")) {
            data.add("是");
        }
        SwingBindings.createJComboBoxBinding(UpdateStrategy.READ, data, jcbShare).bind();
        jcbShare.setSelectedItem("是".equals(empAnalysePara.getCommAnalyseScheme().getShare_flag()) ? "是" : "否");
        lblType.setEnabled(data.contains("是"));
        jcbType.setEnabled(data.contains("是"));
        jcbType.setSelectedItem(empAnalysePara.getCommAnalyseScheme().getShare_type());
        ComponentUtil.setSysFuntionNew(this, false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jcbShare = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        jcbType = new javax.swing.JComboBox();

        jLabel1.setText("名称：");

        jTextField1.setText("jTextField1");

        jLabel2.setText("类别：");

        jLabel3.setText("是否共享：");

        lblType.setText("共享方式：");

        jcbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "所有人", "手动指定" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblType)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbShare, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                .addGap(124, 124, 124))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbShare, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblType)
                    .addComponent(jcbType, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(151, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox jcbShare;
    private javax.swing.JComboBox jcbType;
    private javax.swing.JLabel lblType;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean isValidate() {
        if (jTextField1.getText() == null || jTextField1.getText().replace(" ", "").equals("")) {
            MsgUtil.showInfoMsg(PayAnalyseMsg.msg019);
            return false;
        }
        String hql = "select 1 from " + empAnalysePara.getCommAnalyseScheme().getClass().getSimpleName() + " pas where pas.scheme_name='" + jTextField1.getText() + "' and pas.commAnalyseScheme_key<>'" + empAnalysePara.getCommAnalyseScheme().getCommAnalyseScheme_key() + "' and user_code='" + UserContext.person_code + "'";
        String group = (jComboBox1.getSelectedItem() == null) ? "" : jComboBox1.getSelectedItem().toString();
        if (!group.equals("")) {
            hql = hql + " and group_name='" + group + "' ";
        }
        if (CommUtil.exists(hql)) {
            MsgUtil.showInfoMsg(PayAnalyseMsg.msg028);
            return false;
        }
        return true;
    }

    @Override
    public void beforeLeave() {
        empAnalysePara.getCommAnalyseScheme().setShare_flag((String) jcbShare.getSelectedItem());
        empAnalysePara.getCommAnalyseScheme().setShare_type((String) jcbType.getSelectedItem());
        empAnalysePara.getCommAnalyseScheme().setScheme_name(jTextField1.getText());
        empAnalysePara.getCommAnalyseScheme().setGroup_name((jComboBox1.getSelectedItem() == null) ? "" : jComboBox1.getSelectedItem().toString());

    }

    @Override
    public String getTitle() {
        return PayAnalyseMsg.ttl037.toString();
    }

    @Override
    public String getModuleCode() {
        return module_code;
    }
}
